name: functional_data_generator
version: 2.0.0
description: >-
  Simple and non-intrusive code generator for boilerplate of data types.
homepage: https://github.com/spkersten/dart_functional_data

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  analyzer: '>=2.0.0 <6.0.0'
  build: ^2.0.1
  collection: ^1.15.0
  functional_data: ^1.0.0
  source_gen: ^1.2.7

dev_dependencies:
  build_resolvers: "^2.0.2"
  build_runner: ^2.2.0